
on:
  schedule:
    - cron: '3-59/5 * * * *'
  push:
    branches: main

name: refresh-data

jobs:
  refresh-data:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install httr
        run: Rscript -e 'install.packages(c("httr"))'

      - name: Get data
        run: Rscript -e 'source("sydney.R", echo = TRUE)'

      - name: Commit
        run: |
          git config --global user.name 'Nick Twort'
          git config --global user.email 'nwbort@github.com'
          git add .
          git commit -m 'refreshing data' || echo "No changes to commit"
          git push || echo "No changes to commit"
